postgres:
  restart: always
  environment:
    - CONTAINERBUDDY=file://etc/containerbuddy.json
  expose:
    - 5432
  build: .
  links:
    - consul:consul

consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1
